CREATE TABLE `auto_field_data` (
  `id` int(11) NOT NULL,
  `stringkey` text,
  `tablekey` text,
  `tablekeyno` text,
  `placement` smallint(6) NOT NULL DEFAULT '0',
  `lang_code` text,
  `field_reference` text,
  `field_reference2` text,
  `field_reference3` text,
  `param1` text,
  `param2` text,
  `lang_category` text,
  `checkbox` tinyint(4) NOT NULL DEFAULT '0',
  `funct_call` text
(1, 'wordbyword', '', '--alvah_va_Saya-yi_Mubarikih--Hidden Words--', -1, 'en', '', 'Note1: Put tablekey as specific book if want to limit it to a given book\r\nNote2: from tablekeyno Already cached so commenting this out for --Hidden Words--if need automation done on new proofread copy, remove the book\'s title', 'Note3: Put as Persian to limit to fields with this name; otherwise works on all regular fa (from lang_category) fields (in field_data)', 'Persian', 'English', 'fa', 0, 'wordbyword'),
(2, 'wordbyword1', '', '--alvah_va_Saya-yi_Mubarikih--Hidden Words--', -1, 'en', '', '', '', 'Persian', 'bcode', 'fa', 0, 'wordbyword'),
(3, 'googlify', '', '--Collins--alvah_va_Saya-yi_Mubarikih--wwtf--', -1, '', '', '', '', '', '', '', 0, 'googlify'),
(4, 'googledefine', '', '--alvah_va_Saya-yi_Mubarikih--wwtf--', -1, '', '', '', '', 'define:', '', '', 0, 'googlify'),
(5, 'wordbyword2', '', '--alvah_va_Saya-yi_Mubarikih--Hidden Words--', -1, 'fa', '', '', '', 'Persian', 'Persian', 'fa', 0, 'wordbyword'),
(6, 'wikify', '', '', -1, '', '', '', '', '', '', '', 0, 'wikify'),
(7, 'wikilinks', '', '', 0, '', '', '', '', '', '', '', 1, 'wikilinks'),
(8, 'alias_fielding1', 'Bible', '', 0, 'en', '', '', '', '', '', '', 1, 'alias_fielding'),
(9, 'alias_fielding2', 'quran', '', 0, 'en', '', '', '', '', '', '', 1, 'alias_fielding');
