const colors = [
  'aqua',
  'black',
  'blue',
  'fuchsia',
  'gray',
  'green',
  'lime',
  'maroon',
  'navy',
  'olive',
  'purple',
  'red',
  'silver',
  'teal',
  'white',
  'yellow'
];
const fonts = [
  'Helvetica, sans-serif',
  'Verdana, sans-serif',
  'Gill Sans, sans-serif',
  'Avantgarde, sans-serif',
  'Helvetica Narrow, sans-serif',
  'sans-serif',
  'Times, serif',
  'Times New Roman, serif',
  'Palatino, serif',
  'Bookman, serif',
  'New Century Schoolbook, serif',
  'serif',
  'Andale Mono, monospace',
  'Courier New, monospace',
  'Courier, monospace',
  'Lucidatypewriter, monospace',
  'Fixed, monospace',
  'monospace',
  'Comic Sans, Comic Sans MS, cursive',
  'Zapf Chancery, cursive',
  'Coronetscript, cursive',
  'Florence, cursive',
  'Parkavenue, cursive',
  'cursive',
  'Impact, fantasy',
  'Arnoldboecklin, fantasy',
  'Oldtown, fantasy',
  'Blippo, fantasy',
  'Brushstroke, fantasy',
  'fantasy'
];
export {colors, fonts};
